### ISSUE TITLE
是否可用于勒索病毒？

### ISSUE THREAD

**Issue by freedom-wy** [jan-bar/EncryptionFile#1]
勒索病毒是不是也用的类似方法，加密后无法解密，要解密先拿赎金

**Comment by jan-bar** [comment]
按道理是可以的，甚至可用看看upx源码，将勒索病毒加密到可执行程序里面，执行时解密实际运行程序。我只是提供一种没有私钥无法解密的实现方案额。如果勒索病毒运行到用户电脑，那也得保护私钥不被泄露吧。
